---
openstack_api_versions:
  \"identity\": 3

os_env:
  OS_AUTH_TYPE: v3password
  OS_AUTH_URL: https://{{ ansible_fqdn }}:5000/v3
  OS_USERNAME: admin
  OS_PASSWORD: password
  OS_PROJECT_NAME: admin
  OS_USER_DOMAIN_ID: default
  OS_PROJECT_DOMAIN_ID: default
  OS_IDENTITY_API_VERSION: 3

