---
- name: list groups
  command:  openstack group list -c Name -f csv
  environment: os_env
  register: os_groups
  changed_when: false

- name: list roles
  command: openstack role list -c Name -f csv
  environment: os_env
  register: os_roles
  changed_when: false

- name: list services
  command:  openstack service list -c Name -f csv
  environment: os_env
  register: os_services
  changed_when: false

- name: list projects
  command:  openstack project list -c Name -f csv
  environment: os_env
  register: os_projects
  changed_when: false

- name: list endpoints
  command:  openstack endpoint list -c "Service Name" -c "Interface" -f csv
  environment: os_env
  register: os_endpoints
  changed_when: false

- name: admins group
  command: openstack group create admins
  environment: os_env
  when: '"\"admins\"" not in os_groups.stdout_lines'

- name: ipausers group
  command: openstack group create ipausers
  environment: os_env
  when: '"\"ipausers\"" not in os_groups.stdout_lines'

- name: services group
  command: openstack group create services
  environment: os_env
  when: '"\"services\"" not in os_groups.stdout_lines'

- name: create Member role
  command: openstack role create Member
  environment: os_env
  when: '"\"Member\"" not in os_roles.stdout_lines'

- name: create service role
  command: openstack role create service
  environment: os_env
  when: '"\"Member\"" not in os_roles.stdout_lines'

- name: add creator role
  command: openstack role create creator
  environment: os_env
  when: '"\"creator\"" not in os_roles.stdout_lines'

- name: add observer role
  command: openstack role create observer
  environment: os_env
  when: '"\"observer\"" not in os_roles.stdout_lines'

- name: add audit role
  command: openstack role create audit
  environment: os_env
  when: '"\"audit\"" not in os_roles.stdout_lines'

- name: Member role on demo project
  command: openstack role add --project demo --group ipausers Member
  environment: os_env

- name: service role on services project
  command: openstack role add --project services --group services service
  environment: os_env

- name: list idps
  command: openstack identity provider list -c ID -f csv
  environment: os_env
  register: os_idps
  changed_when: false

- name: list mappings
  command: openstack mapping list -c ID -f csv
  environment: os_env
  register: os_mappings
  changed_when: false
