---
- name: list groups
  command:  openstack group list -c Name -f csv
  environment: os_env
  register: os_groups
  changed_when: false

- name: list roles
  command: openstack role list -c Name -f csv
  environment: os_env
  register: os_roles
  changed_when: false

- name: group
  command: openstack group create admins
  environment: os_env
  when: '"\"admins\"" not in os_groups.stdout_lines'

- name: ipausers group
  command: openstack group create ipausers
  environment: os_env
  when: '"\"ipausers\"" not in os_groups.stdout_lines'

- name: create Member role
  command: openstack role create Member
  environment: os_env
  when: '"\"Member\"" not in os_roles.stdout_lines'

- name: role on demo project
  command: openstack role add  --project demo --group ipausers Member
  environment: os_env

- name: list idps
  command: openstack identity provider list -c ID -f csv
  environment: os_env
  register: os_idps
  changed_when: false

- name: list mappings
  command: openstack mapping list -c ID -f csv
  environment: os_env
  register: os_mappings
  changed_when: false
